name: Trigger auto deployment for ai-product-search-service

on:
  push:
    branches: 
      - master
    paths:
      - '**'
      - '.github/workflows/ai-product-search-service-AutoDeployTrigger-3d91bcae-62f1-49ae-b22e-20b5088fa628.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # Checkout repository
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AIPRODUCTSEARCHSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AIPRODUCTSEARCHSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AIPRODUCTSEARCHSERVICE_AZURE_SUBSCRIPTION_ID }}

      # Docker Hub login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.AIPRODUCTSEARCHSERVICE_REGISTRY_USERNAME }}
          password: ${{ secrets.AIPRODUCTSEARCHSERVICE_REGISTRY_PASSWORD }}

      - name: Build and push base image
        run: |
          echo "ðŸš€ Building and pushing base image..."
          docker build -t depak7/base-ai-search-service:latest -f Dockerfile.base .
          docker push depak7/base-ai-search-service:latest

    
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.AIPRODUCTSEARCHSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AIPRODUCTSEARCHSERVICE_REGISTRY_PASSWORD }}
          containerAppName: ai-product-search-service
          resourceGroup: deepak_space
          imageToBuild: depak7/ai-product-search-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
